### ISSUE TITLE
Errata for the book

### ISSUE THREAD

**Issue by asianfilm** [scalingexcellence/scrapybook-2nd-edition#1]
Hi Dimitrios

Is there a place where we can submit errata for the second edition?

If here, do you want errata references by page number of the book (given in square brackets at page bottom), or page number of the PDF. I presume the former is more stable between revisions.

**Comment by lookfwd** [comment]
Hello Stephen, could you e-mail me on lookfwd@gmail.com? We will have to do this a bit iteratively. :)
